name: UnitTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PHPUnit tests
      uses: graychen/phpunit-action@v1.0.0
      with:
        config: Implementierung/phpunit.xml
    
   
